### ISSUE TITLE
Override System Enhancement 

### ISSUE THREAD

**Issue by thatman84** [libretro/libretro-meta#106]
Request to enhance the override system to allow overrides per content directory. 

To avoid problems associated with content stored in subfolders a "parent" folder option may be required. Many CD based console often have multiple files meaning generally users will store games in subfolders.

E.g. 
If all your content structure is Emulation\ [platform]\game.zip it'd be fine, but if it was Emulation \[platform] \ [game title]\game.cue + game.bin it wouldn't
(Ref Zombeaver)

If completed this feature will allow for custom settings per "system" for the multi system emulator cores. 

Ref https://github.com/libretro/RetroArch/issues/5100

**Comment by thatman84** [comment]
Made a bounty

**Comment by Kondorito** [comment]
+1 for this enhancement!

**Comment by thatman84** [comment]
Does this PR complete the issue? https://github.com/libretro/RetroArch/pull/6775

The bounty can probably be claimed if so

**Comment by thatman84** [comment]
@fr500 completed this issue :)

**Comment by nosh01** [comment]
Agreed that my activity is spotty @thatman84 , wish i was less busy sometimes. @fr500 did a majority of the work anyways so I am happy he was awarded the bounty :)

**Comment by andres-asm** [comment]
thanks :P I spent it already
