### ISSUE TITLE
some arm64 cores vended by buildbot are actually x86_64

### ISSUE THREAD

**Issue by lourinaldi** [libretro/libretro-meta#121]
This is still a problem as of 3:30pm Eastern US time on 3/26/2021

http://buildbot.libretro.com/nightly/apple/osx/arm64/latest/

steps to verify: 

```wget http://buildbot.libretro.com/nightly/apple/osx/arm64/latest/gpsp_libretro.dylib.zip ; unzip gpsp_libretro.dylib.zip ; file gpsp_libretro.dylib```

> gpsp_libretro.dylib: Mach-O 64-bit dynamically linked shared library x86_64

repeat for mednafen_snes, mednafen_vb, fmsx, race, stella, yabause, etc.

**Comment by lourinaldi** [comment]
Full list of impacted cores:

cap32_libretro.dylib:                     Mach-O 64-bit dynamically linked shared library x86_64
fmsx_libretro.dylib:                      Mach-O 64-bit dynamically linked shared library x86_64
gpsp_libretro.dylib:                      Mach-O 64-bit dynamically linked shared library x86_64
lowresnx_libretro.dylib:                  Mach-O 64-bit dynamically linked shared library x86_64
mednafen_snes_libretro.dylib:             Mach-O 64-bit dynamically linked shared library x86_64
mednafen_vb_libretro.dylib:               Mach-O 64-bit dynamically linked shared library x86_64
race_libretro.dylib:                      Mach-O 64-bit dynamically linked shared library x86_64
stella_libretro.dylib:                    Mach-O 64-bit dynamically linked shared library x86_64
vemulator_libretro.dylib:                 Mach-O 64-bit dynamically linked shared library x86_64
yabause_libretro.dylib:                   Mach-O 64-bit dynamically linked shared library x86_64

**Comment by MaddTheSane** [comment]
My guess is the build system is basing the architecture on the build system, which is most likely a (virtual) x86_64 Mac, instead of the targeted architecture.

**Comment by lourinaldi** [comment]
Looks like this has now been resolved.
