### ISSUE TITLE
Build issue for Android ndk

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/libretro-meta#35]
_From @meancoot on August 30, 2012 0:1_

There is an issue with building this for Android. With INCDIRS using the -I${PATH} form the build system will eventually pick up gambatte's memory.h in place of Android's file with the same name.

The simple fix is to replace all entries in INCDIRS with the -iqoute ${PATH} form, then change <gambatte.h> to "gambatte.h" in libretro.cpp.

The environment I use to build is 'platform=unix CC=arm-linux-androideabi-gcc CXX=arm-linux-androideabi-g++'

_Copied from original issue: libretro/gambatte-libretro#3_

**Comment by sergiobenrocha2** [comment]
_From @twinaphex on August 30, 2012 3:5_

True, it's once again a big mistake these codebases make by naming their custom headers the same as system headers. I wonder how we can persuade them to stop doing this for portability's sake.

Thanks for the heads up - the Android port will be the main focus of the next versioned release so any help on this front is most certainly welcome

**Comment by sergiobenrocha2** [comment]
is this still an issue?

**Comment by meepingsnesroms** [comment]
memory.h was renamed to gambatte-memory.h
