### ISSUE TITLE
[WiiU] Version 1.5.0 crashes on subsequent loading

### ISSUE THREAD

**Issue by roflcopter777** [libretro/libretro-meta#66]
Since all the issues that have been reported for the Wii U version are all gone after the merge (which wasn't announced anywhere, mind you). I'm going to report it here once again. 

Version of RetroArch:  
Version 1.5.0 vanilla, no nightly builds were used. 
Loaded Homebrew Launcher via Haxchi hack. 

What should happen: Emulator loaded fine first time, should load every consecutive time that it's launched without issue, but instead it crashes with a system memory error. 

What happens instead: Displays this error message

![20170309_131958](https://cloud.githubusercontent.com/assets/15101626/23817028/6c738112-05ad-11e7-8ca7-5686513c1008.jpg)

I made a config file, closed the app, opened it up again and it displayed this error, I will make a video if need be to show that this occurs. 

Last working version: 1.4.0, many builds including 1.4.1, have been very unstable resulting in system memory errors.

**Comment by andres-asm** [comment]
RetroArch issues still belong in the other repo, I think I disabled the tracker accidentaly sorry about the inconvenience.

**Comment by roflcopter777** [comment]
Meh it happens though.  No worries.
