### ISSUE TITLE
Restarting PCSX core causes crash

### ISSUE THREAD

**Issue by Gurk232** [libretro/libretro-meta#68]
As of 1.5 RetroArch crashes when attempting to restart the PCSX Rearmed core, I have the latest version of the PCSX core as downloaded by the updater, and it does this on all games I have tested.

It did not do this in 1.4.1, so it was working before.

**Comment by Gurk232** [comment]
One thing I forgot to mention, restarting PCSX does not cause it to hard crash, instead RA simply stops responding.

**Comment by hizzlekizzle** [comment]
I suspect this is the culprit:
https://github.com/libretro/pcsx_rearmed/commit/53e4a7e5cb46ad8589825ec95e15b56614cc54d9

**Comment by Gurk232** [comment]
If that is indeed the cause, good eye :)

**Comment by meepingsnesroms** [comment]
Thats it, this is exactly why I put the fix there in the first place.

**Comment by Gurk232** [comment]
So is it possible to fix this?

**Comment by meepingsnesroms** [comment]
Yes, that patch needs to be put back for now until a proper fix is found.

**Comment by Gurk232** [comment]
Alright, hey thanks for both your guys help!

**Comment by Gurk232** [comment]
Any progress on this?

**Comment by meepingsnesroms** [comment]
This is not an Android issue it happens on Mac too before my patch.

**Comment by Gurk232** [comment]
Apologies​, I just always list my platform as to give as much information as possible.

**Comment by Gurk232** [comment]
Just wanted to check back again and see if there was any progress.

**Comment by meepingsnesroms** [comment]
@twinaphex Can I put the rebootemu hack back?
This happens on mac os too and it takes down the whole computer, you cant even force close the window, and this is running in user mode not as root!

**Comment by meepingsnesroms** [comment]
This only happens when using the official bios, using hle it resets fine.

**Comment by Gurk232** [comment]
Last I checked it works correctly now, thank you very much for the help meepingsnesroms.
