### ISSUE TITLE
Move all the core issues to libretro-meta

### ISSUE THREAD

**Issue by andres-asm** [libretro/libretro-meta#78]
We should continue moving all the core issues to libretro-meta to have a single point to track everything
https://github-issue-mover.appspot.com/

**Comment by RobLoach** [comment]
https://github.com/google/github-issue-mover

**Comment by thatman84** [comment]
Who can do this? I guess there is a level of access needed

**Comment by john-parton** [comment]
GitHub now has a "Transfer issue" feature. More info here: https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository

**Comment by keithbowes** [comment]
It seems that would make it far harder to search and report issues, for developers of cores to be notified about them, to close issues in PRs, etc.

**Comment by RobLoach** [comment]
I agree... As a core maintainer, I want issues relating to one core to belong to that core's project. I'd rather use something like [the Issue report](https://github.com/issues?q=is%3Aopen+is%3Aissue++archived%3Afalse+user%3Alibretro+), or [GitHub Projects](https://docs.github.com/en/issues/trying-out-the-new-projects-experience/about-projects).
