### ISSUE TITLE
[Snes9x] Porting latest change regarding SMP bugfix in main fork

### ISSUE THREAD

**Issue by lightgod87** [libretro/libretro-meta#85]
Hi, guys,

The motive of this issue is about this problem which was detected, then acknowledged by byuu:

https://board.byuu.org/viewtopic.php?f=8&t=1665&p=42735#p42735

In the main Snes9x fork on GitHub, there's already a fix for this issue:

https://github.com/snes9xgit/snes9x/commit/fe6047213be802cb74cac724a1b83b7263c4dcca

Is it possible to port this change to the Snes9x libretro core?

**Comment by sergiobenrocha2** [comment]
See PR libretro/snes9x#57
