### ISSUE TITLE
[SNES9x] Sound completely broken in Jungle no Ouja Tar-chan; not an issue in SNES9x-2010

### ISSUE THREAD

**Issue by MapleStoryPSN** [libretro/libretro-meta#86]
Randomly fired the game up on my Pi 3 earlier and noticed right away that there were problems with the audio. Switched over to lr-snes9x-2010 to test and sound works perfectly.

**Comment by hizzlekizzle** [comment]
Could be related to this:
https://github.com/libretro/snes9x/commit/aa92ae172b80b93c22fcf84078e8ad07ec64fedf

**Comment by hizzlekizzle** [comment]
Is this still an issue? That is, does the problem persist in recent builds?

**Comment by hizzlekizzle** [comment]
Is this still an issue? That is, does the problem persist in recent builds?

**Comment by nikkoman** [comment]
Nope, recent build works fine on my RPi 3
