### ISSUE TITLE
No Online Updater

### ISSUE THREAD

**Issue by Zoklar** [libretro/libretro-meta#98]
Please help! My Retroarch does not show the online updater option. I have 1.6.7 on RasPi w/ Retropie.

Thanks

**Comment by hizzlekizzle** [comment]
Try going to settings > user interface > show advanced settings ON and then settings > user interface > views and make sure 'show online updater' is ON.

**Comment by Zoklar** [comment]
That did it hizzlekizzle! Thank you! I'm still learning how to geek with it. Take care ;-)
